- name: Add zot Helm repo chart
  kubernetes.core.helm_repository:
    name: project-zot
    repo_url: http://zotregistry.dev/helm-charts

- name: Deploy zot
  kubernetes.core.helm:
    name: project-zot
    chart_ref: project-zot/zot
    release_namespace: zot
    create_namespace: true
    kubeconfig: /home/vagrant/.kube/config
    values:
      image:
        repository: ghcr.io/project-zot/zot-linux-arm64
      service:
        type: ClusterIP

- name: Create a zot ingressRoute
  kubernetes.core.k8s:
    kubeconfig: /home/vagrant/.kube/config
    state: present
    definition:
      apiVersion: traefik.io/v1alpha1
      kind: IngressRoute
      metadata:
        name: zot.test.lab
        namespace: zot
      spec:
        entryPoints:
          - web
        routes:
          - match: Host(`zot.test.lab`)
            kind: Rule
            services:
              - name: project-zot
                port: 5000